# Numpy Assignments

1. What is a Python library? Why do we use Python libraries?

A Python library is a collection of modules and functions that extend the capabilities of the Python programming language. Libraries are designed to be reusable pieces of code that can be easily integrated into your own programs. They provide pre-written functionality to help you perform tasks without having to write the code from scratch.

Some Examples are:
Numpy,Pandas,Matplotlib,Requests etc..

Here are some reasons why do we use Python Libraries:-

i.Code Reusibility:-Libraries contain pre-written code, saving developers time and effort by allowing them to reuse existing solutions rather than reinventing the wheel.

ii.Productivity: Libraries provide abstractions and high-level interfaces, making complex tasks simpler and more manageable. This improves overall development speed.

iii.Specialized Functionality: Many libraries are designed to solve specific problems or provide specialized functionality. Using these libraries allows developers to leverage the expertise of those who created them.

iv.Performance Optimization: Libraries often include optimized code and algorithms, resulting in better performance than if you were to implement the same functionality manually.

2. What is the difference between Numpy array and List?

The difference between Numpy array and Python Lists are:

i.Data Type:-

.NumPy arrays are homogeneous, meaning all elements of the array must be of the same data type. This allows for more efficient storage and operations.

.Python lists can contain elements of different data types, making them more flexible but potentially less memory-efficient for numerical operations.

ii.Performance:-

.NumPy arrays are implemented in C and provide better performance for numerical operations compared to Python lists. NumPy operations are often faster because they are optimized and performed at the C level.

.Python lists are more general-purpose and versatile but may be slower for numerical computations, especially when dealing with large datasets.

iii.Memory Overhead:-

.NumPy arrays have less memory overhead compared to Python lists. NumPy uses a fixed, pre-allocated block of memory, whereas Python lists need additional memory for each element and its associated Python object overhead.

.NumPy arrays are more memory-efficient when dealing with large datasets.

iv.Syntax:-

.NumPy syntax is more concise and optimized for numerical operations, making it easier to work with large datasets and perform complex mathematical computations.

.Python lists have a simpler syntax and are easier to use for general-purpose tasks. They are more intuitive for beginners but may be less efficient for certain numerical operations.

3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]



In [5]:
import numpy as np

array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

shape=array.shape
size=array.size
dimension=array.ndim

print("Shape of the array:",shape)
print("Size of the array:",size)
print("Dimension of the array:",dimension)

Shape of the array: (3, 4)
Size of the array: 12
Dimension of the array: 2


4. Write python code to access the first row of the following array?

 [[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [7]:
import numpy as np

my_array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

first_row=my_array[0]
print("The first row of the array:",first_row)

The first row of the array: [1 2 3 4]


5. How do you access the element at the third row and fourth column from the given numpy array?

 [[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]



In [8]:
import numpy as np

my_array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

specified_ele=my_array[2][3]
print("The third row and fourth column element:",specified_ele)

The third row and fourth column element: 12


6. Write code to extract all odd-indexed elements from the given numpy array?

 [[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]



In [10]:
my_arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
odd_indexed_ele=my_arr[:,1::2]
print('Odd indexed elements:',odd_indexed_ele)

Odd indexed elements: [[ 2  4]
 [ 6  8]
 [10 12]]


7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [14]:
random_matrix=np.random.rand(3,3)
print("Random 3x3 matrix between the values of 0 and 1 is:")
print(random_matrix)

Random 3x3 matrix between the values of 0 and 1 is:
[[0.85366911 0.85838637 0.51700885]
 [0.10053196 0.98542971 0.71847276]
 [0.11037523 0.83228791 0.06053277]]


8. Describe the difference between np.random.rand and np.random.randn?

9. Write code to increase the dimension of the following array?

 [[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [17]:
arr=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

extendend_dim=np.expand_dims(arr,axis=1)
print("original array:",arr)
print("After extending dimensions")
print(extendend_dim)

original array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
After extending dimensions
[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]


10. How to transpose the following array in NumPy?

 [[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]




In [20]:
original_arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
transpose_arr=original_arr.T
print("The original array:")
print(original_arr)
print("The transpose array:")
print(transpose_arr)

The original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
The transpose array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consider the following matrix:

Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
    
Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
    

Perform the following operation using Python

i.Index wise multiplication

ii.Matrix multiplication

iii.Add both the matrics

iv.Subtract matrix B from A

v.Divide Matrix B by A



In [24]:
Mat_A=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
Mat_B=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Matrix A:")
print(Mat_A)
print("Matrix B:")
print(Mat_B)
#Index Wise Multiplication
Index_wise_Mul=Mat_A*Mat_B

print("The index wise multiplication:")
print(Index_wise_Mul)

#Matrix Multiplication
#The Question is Wrong As the Matrix Multiplication cannot be done in such dimensions

#Add Both Matrics
Addition=Mat_A+Mat_B
print("After Adding Both Matrix:")
print(Addition)

#Subtract Matrix B from A
subtract=Mat_A-Mat_B
print("After Substracting B From A:")
print(subtract)

#Divide Matrix B by A
divide=Mat_B/Mat_A
print("After dividing Matrix B by A:")
print(divide)

Matrix A:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Matrix B:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
The index wise multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
After Adding Both Matrix:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
After Substracting B From A:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
After dividing Matrix B by A:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


12. Which function in Numpy can be used to swap the byte order of an array?

In NumPy, the byteswap() function can be used to swap the byte order of an array. This function changes the endianness (byte order) of the array elements. It is useful when working with binary data and dealing with systems that have different endianness.

#Example:-

In [25]:
original_array = np.array([1, 2, 3, 4], dtype=np.int32)

swapped_array = original_array.byteswap()

print("Original Array:\n", original_array)
print("Swapped Byte Order Array:\n", swapped_array)

Original Array:
 [1 2 3 4]
Swapped Byte Order Array:
 [16777216 33554432 50331648 67108864]


13. What is the significance of the np.linalg.inv function?

The np.linalg.inv function in NumPy is used to compute the multiplicative inverse of a matrix. 

Specifically, given a square matrix A, the function returns another matrix A_inv such that the product of A and A_inv is the identity matrix.

Example:-

In [27]:
A = np.array([[4, 7],
              [2, 6]])

A_inv = np.linalg.inv(A)

identity_matrix = np.dot(A, A_inv)

print("Original Matrix A:\n", A)
print("Inverse Matrix A_inv:\n", A_inv)
print("Verification (A * A_inv):\n", identity_matrix)


Original Matrix A:
 [[4 7]
 [2 6]]
Inverse Matrix A_inv:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
Verification (A * A_inv):
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


14. What does the np.reshape function do, and how is it used?

The np.reshape function in NumPy is used to change the shape of an array without changing its data. It allows you to specify the new shape (dimensions) that you want for the array. The reshaping operation creates a new view of the original array with the specified shape, and it does not modify the original array's data.

The basic Syntax is numpy.reshape(array,newshape)

Example:-

In [28]:
original_array = np.arange(12)

reshaped_array = np.reshape(original_array, (3, 4))

print("Original Array (1D):\n", original_array)
print("\nReshaped Array (3x4):\n", reshaped_array)


Original Array (1D):
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped Array (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


15. What is broadcasting in Numpy?


Broadcasting in NumPy is a powerful mechanism that allows arrays of different shapes to be combined and operated upon. It provides a way to perform element-wise operations on arrays of different shapes without explicitly reshaping them. Broadcasting automatically expands the smaller array to match the shape of the larger one, making certain operations more convenient and efficient.

Example:-

In [29]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_addition = matrix + np.array([10, 20, 30])
print("Original Matrix:\n", matrix)
print("\nRow Addition using Broadcasting:\n", row_addition)

Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Row Addition using Broadcasting:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]
